name: Policy Controller

on:
  pull_request:
    paths:
      - 'policy-controller/**'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./policy-controller/

jobs:
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.54.0
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  audit:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    # Prevent sudden announcement of a new advisory from failing Ci.
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - run: |
          v=0.9.1
          url="https://github.com/EmbarkStudios/cargo-deny/releases/download/$v/cargo-deny-$v-x86_64-unknown-linux-musl.tar.gz"
          cd ~/.cargo/bin
          curl -vsLo - "$url" |tar --strip-components=1 -zxf - "cargo-deny-$v-x86_64-unknown-linux-musl/cargo-deny"
      - run: cargo deny check ${{ matrix.checks }}

  clippy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.54.0
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - run: rustup component add clippy
      - run: cargo clippy --all-targets

  check:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.54.0
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - run: cargo check

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: docker://rust:1.54.0-buster
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - run: mkdir -p target && cd target && curl -vsL https://github.com/xd009642/tarpaulin/releases/download/0.18.0/cargo-tarpaulin-0.18.0-travis.tar.gz | tar zxvf - && chmod 755 cargo-tarpaulin
      - run: target/cargo-tarpaulin tarpaulin --workspace --out Xml
      - uses: codecov/codecov-action@51d810878be5422784e86451c0e7c14e5860ec47
        with:
          flags: unittests,rust
